// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateTableReducer from "../create_table_reducer";
import DeleteEntityReducer from "../delete_entity_reducer";
import JoinTableReducer from "../join_table_reducer";
import MoveEntityReducer from "../move_entity_reducer";
import RunPendingMigrationsReducer from "../run_pending_migrations_reducer";
import SetEntityHiddenReducer from "../set_entity_hidden_reducer";
import SpawnEntityReducer from "../spawn_entity_reducer";

export type CreateTableParams = __Infer<typeof CreateTableReducer>;
export type DeleteEntityParams = __Infer<typeof DeleteEntityReducer>;
export type JoinTableParams = __Infer<typeof JoinTableReducer>;
export type MoveEntityParams = __Infer<typeof MoveEntityReducer>;
export type RunPendingMigrationsParams = __Infer<typeof RunPendingMigrationsReducer>;
export type SetEntityHiddenParams = __Infer<typeof SetEntityHiddenReducer>;
export type SpawnEntityParams = __Infer<typeof SpawnEntityReducer>;

