// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClearLightsReducer from "../clear_lights_reducer";
import ClearMapImageReducer from "../clear_map_image_reducer";
import ClearWallsReducer from "../clear_walls_reducer";
import CreateTableReducer from "../create_table_reducer";
import DeleteEntityReducer from "../delete_entity_reducer";
import DeletePropReducer from "../delete_prop_reducer";
import ImportLightsReducer from "../import_lights_reducer";
import ImportWallsReducer from "../import_walls_reducer";
import JoinTableReducer from "../join_table_reducer";
import MoveEntityReducer from "../move_entity_reducer";
import MovePropReducer from "../move_prop_reducer";
import RunPendingMigrationsReducer from "../run_pending_migrations_reducer";
import SetEntityHiddenReducer from "../set_entity_hidden_reducer";
import SetMapImageReducer from "../set_map_image_reducer";
import SetPropHiddenReducer from "../set_prop_hidden_reducer";
import SpawnEntityReducer from "../spawn_entity_reducer";
import SpawnPropReducer from "../spawn_prop_reducer";
import UpdatePropParamsReducer from "../update_prop_params_reducer";

export type ClearLightsParams = __Infer<typeof ClearLightsReducer>;
export type ClearMapImageParams = __Infer<typeof ClearMapImageReducer>;
export type ClearWallsParams = __Infer<typeof ClearWallsReducer>;
export type CreateTableParams = __Infer<typeof CreateTableReducer>;
export type DeleteEntityParams = __Infer<typeof DeleteEntityReducer>;
export type DeletePropParams = __Infer<typeof DeletePropReducer>;
export type ImportLightsParams = __Infer<typeof ImportLightsReducer>;
export type ImportWallsParams = __Infer<typeof ImportWallsReducer>;
export type JoinTableParams = __Infer<typeof JoinTableReducer>;
export type MoveEntityParams = __Infer<typeof MoveEntityReducer>;
export type MovePropParams = __Infer<typeof MovePropReducer>;
export type RunPendingMigrationsParams = __Infer<typeof RunPendingMigrationsReducer>;
export type SetEntityHiddenParams = __Infer<typeof SetEntityHiddenReducer>;
export type SetMapImageParams = __Infer<typeof SetMapImageReducer>;
export type SetPropHiddenParams = __Infer<typeof SetPropHiddenReducer>;
export type SpawnEntityParams = __Infer<typeof SpawnEntityReducer>;
export type SpawnPropParams = __Infer<typeof SpawnPropReducer>;
export type UpdatePropParamsParams = __Infer<typeof UpdatePropParamsReducer>;

