// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  EntityKind,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  tableId: __t.u64().name("table_id"),
  dmIdentity: __t.identity().name("dm_identity"),
  get kind() {
    return EntityKind;
  },
  name: __t.string(),
  color: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  rotY: __t.f32().name("rot_y"),
  hidden: __t.bool(),
  createdBy: __t.identity().name("created_by"),
});
