// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Entity = __t.object("Entity", {
  id: __t.u64(),
  tableId: __t.u64(),
  dmIdentity: __t.identity(),
  get kind() {
    return EntityKind;
  },
  name: __t.string(),
  color: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  rotY: __t.f32(),
  hidden: __t.bool(),
  createdBy: __t.identity(),
});
export type Entity = __Infer<typeof Entity>;

// The tagged union or sum type for the algebraic type `EntityKind`.
export const EntityKind = __t.enum("EntityKind", {
  Mini: __t.unit(),
  Prop: __t.unit(),
});
export type EntityKind = __Infer<typeof EntityKind>;

export const GameTable = __t.object("GameTable", {
  id: __t.u64(),
  slug: __t.string(),
  name: __t.string(),
  dmIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type GameTable = __Infer<typeof GameTable>;

export const MigrationState = __t.object("MigrationState", {
  stepKey: __t.string(),
  appliedAt: __t.timestamp(),
});
export type MigrationState = __Infer<typeof MigrationState>;

export const Participant = __t.object("Participant", {
  id: __t.u64(),
  tableId: __t.u64(),
  identity: __t.identity(),
  displayName: __t.string(),
  get role() {
    return Role;
  },
  online: __t.bool(),
});
export type Participant = __Infer<typeof Participant>;

// The tagged union or sum type for the algebraic type `Role`.
export const Role = __t.enum("Role", {
  Dm: __t.unit(),
  Player: __t.unit(),
});
export type Role = __Infer<typeof Role>;

